project:
  type: book
  output-dir: _site
  preview:
    port: 4000
    timeout: 1200

book:
  title: "docs.fordjohnson.dev"
  site-url: https://docs.fordjohnson.dev
  favicon: _components/favicon.png
  # cover-image: images/logo.png
  image: https://cdn.jsdelivr.net/gh/bradfordjohnson/global-assets@master/images/logo/logo.png
  date: last-modified

  sidebar:
    style: docked
    logo: https://cdn.jsdelivr.net/gh/bradfordjohnson/global-assets@master/images/logo/logo.png
    tools:
      - icon: house
        href: https://fordjohnson.dev
        text: Portfolio

  page-footer:
    left: |
      Ford Johnson
    right: |
      Built with ❤️ and <a href="https://quarto.org/">Quarto</a>.

  repo-url: https://github.com/bradfordjohnson/docs.fordjohnson.dev/
  repo-branch: main
  repo-actions: [edit, issue]

  author: "Ford Johnson"

  chapters:
    - index.qmd
    - analysis_methods/index.qmd
    - part: deep_dives/index.qmd
      chapters:
        - deep_dives/rocket_league/index.qmd
        - deep_dives/core_pretzel_index/index.qmd

format:
  html:
    canonical-url: true

    page-layout: full
    css: styles.css
    theme:
      - cosmo
      - brand

    include-in-header: ga4/gtm_header.html
    include-before-body: ga4/gtm_body.html

    grid:
      sidebar-width: 350px
