project:
  type: book
  output-dir: _site

book:
  title: "docs.fordjohnson.dev"
  site-url: docs.fordjohnson.dev
  date: last-modified

  page-footer:
    left: |
      Ford Johnson
    right: |
      Built with ❤️ and <a href="https://quarto.org/">Quarto</a>.

  # cover-image: cover.jpg
  # favicon: cover.jpg

  repo-url: https://github.com/bradfordjohnson/docs.fordjohnson.dev/
  repo-branch: main
  repo-actions: [edit, issue]

  author: "Ford Johnson"

  chapters:
    - index.qmd
    - part: "Test"
      chapters: 
        - intro.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    canonical-url: true
