name: Deploy Quarto site via GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - "docs.fordjohnson.dev/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: latest

      # Optional: install R / Python if you use them
      # - uses: r-lib/actions/setup-r@v2
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.11"

      - name: Render Quarto site
        run: quarto render docs.fordjohnson.dev

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs.fordjohnson.dev/_site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
